name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Set up uv
      uses: astral-sh/setup-uv@v7
      with:
        version: "0.10.4"
        enable-cache: true
        python-version: '3.10'

    - name: Sync dependencies
      run: uv sync --frozen

    - name: Lint with ruff
      run: uv run --no-sync ruff check --output-format=github src/arlmet

    - name: Type checking with pyrefly
      if: ${{ !cancelled() }}
      run: uv run --no-sync pyrefly check src/arlmet

    - name: Check docstring coverage
      if: ${{ !cancelled() }}
      run: uv run --no-sync docstr-coverage src/arlmet --skip-magic --skip-init --skip-property --fail-under 95
